### ISSUE TITLE
netSDK wirft Fehler beim parsen von Serverantwort

### ISSUE THREAD

**Issue by cschondorff** [fiskaly/fiskaly-sdk-dotnet#16]
Moin,

beim Aufruf der Methode Request des FiskalyHttpClients, wird folgender Fehler geworfen:

> After parsing a value an unexpected character was encountered: 1. Path 'message', line 1, position 176.

Folgender Stacktrace dazu:

>    bei Newtonsoft.Json.JsonTextReader.ParsePostValue(Boolean ignoreComments)
   bei Newtonsoft.Json.JsonTextReader.Read()
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   bei Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   bei Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   bei Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   bei Fiskaly.FiskalyHttpClient.CreateFiskalyHttpError[T](JsonRpcResponse`1 response)
   bei Fiskaly.FiskalyHttpClient.ThrowOnError[T](JsonRpcResponse`1 response)
   bei Fiskaly.FiskalyHttpClient.Request(String method, String path, Byte[] body, Dictionary`2 headers, Dictionary`2 query)

Ich wollte via StartTransaction mir einen Beleg mittels folgenden payload  ausstellen lassen:

> "{\"state\":\"ACTIVE\",\"client_id\":\"ClientId entfernt\",\"schema\":{\"standard_v1\":{\"receipt\":{\"receipt_type\":\"RECEIPT\",\"amounts_per_vat_rate\":[{\"vat_rate\":\"19.00\",\"amount\":\"23.42\"}],\"amounts_per_payment_type\":[{\"payment_type\":\"CASH\",\"amount\":\"23.42\",\"currency_code\":\"EUR\"}]}}}}"

Es scheint, dass der Server mir etwas mitteilen möchte, aber das parsen der Antwort schlägt fehl. Mögt ihr einmal schauen, was da schief läuft.

Gruß und Danke im voraus.

**Comment by auxdevelopment** [comment]
Wir konnten die Ursache des Fehlers nun finden. Es handelt sich um einen Client-Bug.

Beim nächsten Release wird dies behoben. Wir bemühen uns um ein baldiges Release.
