### ISSUE TITLE
Fiskaly.Errors.FiskalyHttpError: token's 'exp' has passed or could not parsed

### ISSUE THREAD

**Issue by jenshorch** [fiskaly/fiskaly-sdk-dotnet#21]
O.g. Fehler kommt immer mal wieder.
Wenn ich den gleichen Request sofort erneut schicke klappt er.
Passiert sehr unregelmäßig und war bisher nicht reproduzierbar.

Ich hab nun alle Aufrufe in eine RetryPolicy gepackt. Beim zweiten Versuch klappt der Request dann.

Log sagt: [ERROR] 2020/07/15 15:32:53 debug.go:21: http-status not okay: 401

Version 1.2.000

**Comment by prempador** [comment]
This error should be fixed with v1.2.100. 

Please update and reopen this issue if this error still occurs.
