### ISSUE TITLE
Get a TSS throws an Exception

### ISSUE THREAD

**Issue by sebfischer83** [fiskaly/fiskaly-sdk-dotnet#26]
Hi,

why does 
var getTseResponse = _fiskalyHttpClient.Request("GET", $"/tss/{tssId.ToString()}", null, null, null);
throws an Exception? I think it would be much nicer to check for the StatusCode instead of using catch clauses and the exception don't get the StatusCode so I must the Code field where the strings are not described anywhere.

**Comment by prempador** [comment]
Hello @sebfischer83 , 

Thank you for your report. 
"Throws an exception" is a bit vague, could you maybe tell us what exception? You should also be able to read the message and probably figure out what went wrong yourself. 

We decided to throw Exceptions in case of a negative response. This will not be changed.

**Comment by sebfischer83** [comment]
"We decided to throw Exceptions in case of a negative response. This will not be changed." That answers my question 👍 
Only problem is that this beahvoir isn`t really clear from the documentation.

**Comment by prempador** [comment]
We will keep that in mind when working on the documentation the next time. Thanks for the input.
