### ISSUE TITLE
Error on put Transaction

### ISSUE THREAD

**Issue by stengnath** [fiskaly/fiskaly-sdk-dotnet#28]
„token's 'exp' has passed or could not parsed 'somerandomnumber'

The transaction ist created successfully.
Wenn Updating/finishing the Transaction, the error sometimes ist beeing thrown by the server.
Transaction remeins active.

Not reproducible, next transaction fully ok.

I did write an Email on 12.08.2020 but didn't get any response.

Version: com.fiskaly.client-windows-386-v1.2.000.dll

**Comment by prempador** [comment]
Please update to v1.2.100. This bug should be fixed in the newest version.

**Comment by stengnath** [comment]
ok, thanks a lot.
