### ISSUE TITLE
Internal Error nach Update auf Version 1.2.100

### ISSUE THREAD

**Issue by sebfischer83** [fiskaly/fiskaly-sdk-dotnet#33]
Hallo,

wir haben auf die Version 1.2.100 geupdated und erhalten nun wenn wir z.B. die TSE Informationen abrufen wollen einen Internal Error.
Der Fehler ist:
`failed to fetch remote JWK: Get "https://auth.fiskaly.com/auth/realms/fiskaly/protocol/openid-connect/certs": dial tcp 35.198.188.136:443: connectex: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat.`

Ich vermute das die Proxy Daten nicht genutzt werden in dieser Version.

Version liefert:
```
{SDK: {
	Version: dotnet-v1.2.100
}
Client: {
	Version: 1.2.100,
	CommitHash: 0a8a3c6e83c4c44433d480560f1a3f1a12566e11,
	SourceHash: 0c28227cea801e8fdc811d3a4c72c199763d6254fde1df4be9e51e299b63a672
}
Smaers: {
	Version: 0.1.0,
	CommitHash: ,
	SourceHash: 
}
}
    ClientVersion: {{
	Version: 1.2.100,
	CommitHash: 0a8a3c6e83c4c44433d480560f1a3f1a12566e11,
	SourceHash: 0c28227cea801e8fdc811d3a4c72c199763d6254fde1df4be9e51e299b63a672
}}
    SdkVersion: "dotnet-v1.2.100"
    SmaersVersion: {{
	Version: 0.1.0,
	CommitHash: ,
	SourceHash: 
}}
```
HealthCheck:
```
{{
	Proxy: {
	Status: http://10.1.254.254:800
}
	Smaers: {
	Status: OK
}
	Backend: {
	Status: OK
}
}}
    Backend: {{
	Status: OK
}}
    Proxy: {{
	Status: http://10.1.254.254:800
}}
    Smaers: {{
	Status: OK
}}

```

**Comment by kunstloch** [comment]
Hallo, danke für die Nachricht!
Können Sie überprüfen, ob `auth.fiskaly.com` in der Firewall freigeschaltet wurde?
Die Fehlermeldung klingt nach einer Antwort vom Proxy der `auth.fiskaly.com` nicht erreichen kann.  
Bitte geben Sie uns bescheid, inwieweit der Hinweis geholfen hat.

**Comment by sebfischer83** [comment]
Mit der Version 1.2.0 ist dieses Problem ja nicht vorhanden.

**Comment by kunstloch** [comment]
Für die Version 1.2.100 sollte `auth.fiskaly.com` in der Firewall freigeschalten werden.
Haben Sie das überprüft?

**Comment by sebfischer83** [comment]
Hallo ja hatte ich, seltsamerweise funktioniert nun alles in der Testumgebung, trotz gleicher Bedingungen.  Scheinbar war wirklich ein Problem in unseren Netz schuld.
