### ISSUE TITLE
Payment_type and vat_rate

### ISSUE THREAD

**Issue by phileas1969** [fiskaly/fiskaly-sdk-dotnet#35]
Hi there,

sorry, I have one more question:

What are valid values for payment_type and vat_rate?

Is there somewhere a list?

Best regards and thank you very, very much in advance!!

Phileas

**Comment by cars10w** [comment]
Hi,

at https://developer.fiskaly.com/api/kassensichv/v1/#operation/upsertTransaction just expand all the nodes in the documentation.

Under schema->standard_v1->receipt->amounts_per_vat_rate->vat_rate you will find:

` Enum: "NORMAL" "REDUCED_1" "SPECIAL_RATE_1" "SPECIAL_RATE_2" "NULL" `

And for schema->standard_v1->receipt->amounts_per_payment_type->payment_type:

`Enum: "CASH" "NON_CASH"`

Best regards,
Carsten

**Comment by phileas1969** [comment]
Thank you very much!!!
