### ISSUE TITLE
Invalid Params

### ISSUE THREAD

**Issue by jenshorch** [fiskaly/fiskaly-sdk-dotnet#4]
GET-Request wie in der Readme funktioniert. Aber ich bekomme keine PUT-Requests zum Laufen. Ich erhalte immer einen Fehler -32602 "Invalid Params".

Hier mein Code:
```
var revision = 0;
var txId = Guid.NewGuid();
var url = $"tss/{config.TseId}/tx/{txId}";
var query = new Dictionary<string, string>() { { "last_revision", revision.ToString() } };
var transaction = new Transaction(receipt, (Guid)config.ClientId);
var data = JsonConvert.SerializeObject(transaction);
var response = client.Request("PUT", url, Encoding.UTF8.GetBytes(data), null, query);
```

Was mache ich hier falsch?

**Comment by auxdevelopment** [comment]
Tritt dieser Fehler mit der [aktuellen SDK-Version](https://www.nuget.org/packages/fiskaly-dotnet-sdk/1.1.0-r1) noch auf?

**Comment by jenshorch** [comment]
Ich kann nun Transactions mit Status ACTIVE öffnen und erhalte eine korrekte Antwort. Beim Schließen mit FINISHED kommt der Fehler jedoch immer noch.

**Comment by auxdevelopment** [comment]
Sofern ich das Problem richtig einschätze müssten Sie eine `FiskalyClientError`-Exception erhalten?

Falls dies der Fall ist, bitte ich Sie mir den Inhalt des `Error`-Properties zukommen zu lassen.

**Comment by jenshorch** [comment]
`{
  "Offset": 1
}`

**Comment by auxdevelopment** [comment]
Wäre es möglich, dass Sie uns den Inhalt des `data` Properties zukommen lassen?

**Comment by jenshorch** [comment]
Ich bin einen Schritt weiter. Hauptproblem war der BreakingChange von v0 auf v1. Hab jetzt alle Models angepasst. Nun aber folgender Fehler:

Newtonsoft.Json.JsonReaderException
`Unexpected character encountered while parsing value: H. Path '', line 0, position 0.`

Hier noch der Stacktrace:
`   at Newtonsoft.Json.JsonTextReader.ParseValue()
at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at Fiskaly.FiskalyHttpClient.CreateFiskalyHttpError[T](JsonRpcResponse`1 response)
   at Fiskaly.FiskalyHttpClient.ThrowOnError[T](JsonRpcResponse`1 response)
   at Fiskaly.FiskalyHttpClient.Request(String method, String path, Byte[] body, Dictionary`2 headers, Dictionary`2 query)
   at KassenSichVService.Services.DomainService.SignReceipt(Receipt receipt) in \\Mac\Home\Development\KassenSichVService\Services\DomainService.cs:line 178
   at KassenSichVService.HostedServices.ReceiptHandler.DoWork() in \\Mac\Home\Development\KassenSichVService\HostedServices\ReceiptHandler.cs:line 110`

Folgenden Payload schicke ich hin:
`{
  "state": "ACTIVE",
  "client_id": "c2a10139-c753-40de-bae9-44b7e1c08e39",
  "schema": {
    "standard_v1": {
      "receipt": {
        "receipt_type": "RECEIPT",
        "amounts_per_vat_rate": [
          {
            "amount": "1.0000",
            "vat_rate": "0"
          }
        ],
        "amounts_per_payment_type": [
          {
            "amount": "1.0000",
            "payment_type": "CASH"
          }
        ]
      }
    }
  },
  "metadata": {
    "receiptId": "200048891",
    "receiptType": "Bistroeinzahlung"
  }
}`

Über die API direkt funktioniert das ganze mit o.g. Payload. Soeben in Postman getestet.

**Comment by auxdevelopment** [comment]
Bekommen Sie diesen Fehler mit der [v1.1.200](https://www.nuget.org/packages/fiskaly-dotnet-sdk/1.1.200) des SDKs und des Clients noch immer?

Eine weitere Möglichkeit Ihren Fehler besser verstehen zu können wäre über den [Debug Mode](https://github.com/fiskaly/fiskaly-sdk-dotnet#enabling-the-debug-mode). Können Sie diesen aktivieren und uns die relevanten Informationen des Debug-Logs zukommen lassen?

**Comment by jenshorch** [comment]
Guter Hinweis. Tritt in v1.1.200 immer noch auf. Hier das Log:
`[ERROR] 2020/04/15 14:28:20 request.go:179: HTTP error: {Status: 400, Headers: {"X-Request-Id":["0123456789"]}, Body: amounts_per_vat_rate.0.amount: Does not match pattern '^-?\d+(\.\d{2,64})$'
amounts_per_payment_type.0.amount: Does not match pattern '^-?\d+(\.\d{2,64})$'
}
`

Hier nochmal der Payload meines aktuellen Tests: 
`{"state":"ACTIVE","client_id":"c2a10139-c753-40de-bae9-44b7e1c08e39","schema":{"standard_v1":{"receipt":{"receipt_type":"RECEIPT","amounts_per_vat_rate":[{"amount":"1.0000","vat_rate":"0"}],"amounts_per_payment_type":[{"amount":"1.0000","payment_type":"CASH"}]}}},"metadata":{"receiptId":"200048893","receiptType":"Bistroeinzahlung"}}`

**Comment by jenshorch** [comment]
Soeben Update auf v1.1.300 durchgeführt. Öffnen einer Transaktion funktioniert nun wieder.
Jedoch kommt nun ein Fehler beim Schließen.
[ERROR] 2020/04/17 15:04:13 request.go:154: invalid character 'e' looking for beginning of value
Data-Property enthält ein leeres Dictionary.

**Comment by jenshorch** [comment]
nuget Package ist auf 1.1.301. Gibt es dazu auch aktualisierte Clients? Derzeit noch 1.1.300 unter Downloads verfügbar

**Comment by prempador** [comment]
https://developer.fiskaly.com/downloads#versioning

> Our SDKs and client use Semantic Versioning to provide consistent version information. The SDK version follows the client version, i.e. they must always have the same MAJOR and MINOR version number. The first two numbers of the PATCH must also be the same. Following numbers mark the revisions of the SDK.

**Comment by jenshorch** [comment]
Danke für den Hinweis. Nach Update auf 1.1.301 immer noch gleiches Verhalten. 
"invalid character 'e' looking for beginning of value" beim Versuch eine Transaktion zu schließen.
Öffnen funktioniert.

**Comment by jenshorch** [comment]
Update auf 1.1.400 durchgeführt. Öffnen der Transaktion klappt. Verhalten beim Schließen unverändert.
[ERROR] 2020/04/24 09:13:57 request.go:154: invalid character 'e' looking for beginning of value

Hier nochmal das gesendete JSON:
`{"state":"FINISHED","client_id":"c2a10139-c753-40de-bae9-44b7e1c08e39","schema":{"standard_v1":{"receipt":{"receipt_type":"RECEIPT","amounts_per_vat_rate":[{"amount":"0.0000","vat_rate":"19"}],"amounts_per_payment_type":[{"amount":"0.0000","payment_type":"NON_CASH"}]}}},"metadata":{"receiptId":"200048910","receiptType":"Kassenbeleg"}}`

Exakt dieses Objekt mit Postman gesendet schließt die Transaktion erfolgreich.

Hier noch der Stacktrace:
` 
at Fiskaly.FiskalyHttpClient.ThrowOnError[T](JsonRpcResponse'1 response)
at Fiskaly.FiskalyHttpClient.Request(String method, String path, Byte[] body, Dictionary'2 headers, Dictionary'2 query)
at KassenSichVService.Services.DomainService.SignReceipt(Receipt receipt) in \\Mac\Home\Development\KassenSichVService\Services\DomainService.cs:line 201
at KassenSichVService.HostedServices.ReceiptHandler.ExecuteAsync(CancellationToken stoppingToken) in \\Mac\Home\Development\KassenSichVService\HostedServices\ReceiptHandler.cs:line 61`

**Comment by skbg31** [comment]
bei mir funktioniert es:

```
{
  "receipt": {
    "receipt_type": "RECEIPT",
    "amounts_per_vat_rate": [
      {
        "vat_rate": "19",
        "amount": "0.00"
      }
    ],
    "amounts_per_payment_type": [
      {
        "payment_type": "NON_CASH",
        "amount": "0.00",
        "currency_code": "EUR"
      }
    ]
  }
}
```

**Comment by prempador** [comment]
@jenshorch könnten Sie noch den Base64 String schicken, welchen Sie im Endeffekt an die request Methode übergeben? Vielleicht gibt es ein Problem bei der Konvertierung.

**Comment by jenshorch** [comment]
Welches Base64? Ich habe einen JSON-String, konvertiere den in ein Byte-Array und übergebe dieses an die Request-Methode. Analog zum Beispiel auf der Startseite.

```
var transaction = new Transaction(receipt, (Guid)Config.ClientId);
var data = JsonConvert.SerializeObject(transaction);
var response = client.Request("PUT", url, Encoding.UTF8.GetBytes(data), null, query);
```

**Comment by skbg31** [comment]
Enthält der JSON-String Zeilenumbrüche die dann bei der Konvertierung Probleme verursachen?

`Newtonsoft.Json.JsonConvert.SerializeObject(transaction, **Newtonsoft.Json.Formatting.None**, jsonSerSetting)`

**Comment by jenshorch** [comment]
Nein. Auch mit `Formatting.None` kein Erfolg. Der einzige Unterschied zwischen dem Öffnen und dem Schließen der Transaktion im JSON ist der State. Ansonsten sind das identische Objekte. Öffnen klappt. Schließen nicht.

**Comment by skbg31** [comment]
was steht in der Dictionary query? hier müsste ja dann last_revision = 1 enthalten sein

**Comment by jenshorch** [comment]
korrekt

**Comment by prempador** [comment]
Interessant, wenn Sie sagen, dass es eigentlich der selbe request ist, bis auf den State und wahrscheinlich auch die query. 

Was ich gemeint habe ist das Ergebnis von ```Encoding.UTF8.GetBytes(data)```. Ob Sie mir das zukommen lassen können.

**Comment by jenshorch** [comment]
Ich habe den Fehler gefunden. JSON und query waren in Ordnung. Aber beim Schließen war die Konvertierung in Byte[] nicht ok. Dummer Fehler meinerseits. Jetzt passt alles. Transaktionen werden korrekt abgeschlossen. Vielen Dank für die Bemühungen.
